/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processing_core_PApplet */

#ifndef _Included_processing_core_PApplet
#define _Included_processing_core_PApplet
#ifdef __cplusplus
extern "C" {
#endif
#undef processing_core_PApplet_FOCUS_TRAVERSABLE_UNKNOWN
#define processing_core_PApplet_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef processing_core_PApplet_FOCUS_TRAVERSABLE_DEFAULT
#define processing_core_PApplet_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef processing_core_PApplet_FOCUS_TRAVERSABLE_SET
#define processing_core_PApplet_FOCUS_TRAVERSABLE_SET 2L
#undef processing_core_PApplet_TOP_ALIGNMENT
#define processing_core_PApplet_TOP_ALIGNMENT 0.0f
#undef processing_core_PApplet_CENTER_ALIGNMENT
#define processing_core_PApplet_CENTER_ALIGNMENT 0.5f
#undef processing_core_PApplet_BOTTOM_ALIGNMENT
#define processing_core_PApplet_BOTTOM_ALIGNMENT 1.0f
#undef processing_core_PApplet_LEFT_ALIGNMENT
#define processing_core_PApplet_LEFT_ALIGNMENT 0.0f
#undef processing_core_PApplet_RIGHT_ALIGNMENT
#define processing_core_PApplet_RIGHT_ALIGNMENT 1.0f
#undef processing_core_PApplet_serialVersionUID
#define processing_core_PApplet_serialVersionUID -7644114512714619750LL
#undef processing_core_PApplet_serialVersionUID
#define processing_core_PApplet_serialVersionUID 4613797578919906343LL
#undef processing_core_PApplet_INCLUDE_SELF
#define processing_core_PApplet_INCLUDE_SELF 1L
#undef processing_core_PApplet_SEARCH_HEAVYWEIGHTS
#define processing_core_PApplet_SEARCH_HEAVYWEIGHTS 1L
#undef processing_core_PApplet_serialVersionUID
#define processing_core_PApplet_serialVersionUID -2728009084054400034LL
#undef processing_core_PApplet_serialVersionUID
#define processing_core_PApplet_serialVersionUID -5836846270535785031LL
#undef processing_core_PApplet_THREAD_DEBUG
#define processing_core_PApplet_THREAD_DEBUG 0L
#undef processing_core_PApplet_DEFAULT_WIDTH
#define processing_core_PApplet_DEFAULT_WIDTH 100L
#undef processing_core_PApplet_DEFAULT_HEIGHT
#define processing_core_PApplet_DEFAULT_HEIGHT 100L
#undef processing_core_PApplet_MIN_WINDOW_WIDTH
#define processing_core_PApplet_MIN_WINDOW_WIDTH 128L
#undef processing_core_PApplet_MIN_WINDOW_HEIGHT
#define processing_core_PApplet_MIN_WINDOW_HEIGHT 128L
#undef processing_core_PApplet_EXTERNAL_STOP
#define processing_core_PApplet_EXTERNAL_STOP 115L
#undef processing_core_PApplet_CRUSTY_THREADS
#define processing_core_PApplet_CRUSTY_THREADS 0L
#undef processing_core_PApplet_PERLIN_YWRAPB
#define processing_core_PApplet_PERLIN_YWRAPB 4L
#undef processing_core_PApplet_PERLIN_YWRAP
#define processing_core_PApplet_PERLIN_YWRAP 16L
#undef processing_core_PApplet_PERLIN_ZWRAPB
#define processing_core_PApplet_PERLIN_ZWRAPB 8L
#undef processing_core_PApplet_PERLIN_ZWRAP
#define processing_core_PApplet_PERLIN_ZWRAP 256L
#undef processing_core_PApplet_PERLIN_SIZE
#define processing_core_PApplet_PERLIN_SIZE 4095L
/*
 * Class:     processing_core_PApplet
 * Method:    native_unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_processing_core_PApplet_native_1unload
  (JNIEnv *, jobject);

/*
 * Class:     processing_core_PApplet
 * Method:    native_createGraphics
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_processing_core_PApplet_native_1createGraphics
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     processing_core_PApplet
 * Method:    native_point
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_processing_core_PApplet_native_1point
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     processing_core_PApplet
 * Method:    native_stroke
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_processing_core_PApplet_native_1stroke
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
