/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processing_core_PApplet_Worker */

#ifndef _Included_processing_core_PApplet_Worker
#define _Included_processing_core_PApplet_Worker
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
