/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class processing_core_PApplet_WorkerVar */

#ifndef _Included_processing_core_PApplet_WorkerVar
#define _Included_processing_core_PApplet_WorkerVar
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
